language: java
jdk:
  - oraclejdk7
  #Not yet supported by findbugs.
  #- oraclejdk8
  - openjdk7

#Needed to avoid a problem in travis CI with permission for gradlew.
before_install:
 - chmod +x gradlew

#script: ./gradlew check --debug

